### ISSUE TITLE
CPU/GPU 使用率限制

### ISSUE THREAD

**Issue by ghost** [dovela/xmr-stak-auto#1]
建议做个可以限制 CPU/GPU 使用频率的功能耶， 大佬

**Comment by dovela** [comment]
可以，这个好加

**Comment by wangwill** [comment]
第216行报错

./OneClickMine.sh: line 216: syntax error in conditional expression
./OneClickMine.sh: line 216: syntax error near `]],'
./OneClickMine.sh: line 216: `        if [[ $? == 0 ]], then'

**Comment by dovela** [comment]
知道了，晚上改
